config/routes.rb
Biblioteca::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
   get "sign_in" => "usuarios#new", :as => "sign_in"
  resources :sessions
  resources :testes
  resources :endbiblis
  resources :listbiblis
  resources :autors
  resources :livros
  resources :listbiblis_livros
  resources :autors_livros
  resources :usuarios
  resource :confirmation, :only => [:show]
  resource :usuario_sessions, :only => [:create, :new, :destroy]
  root :to => "homes#index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base
  has_and_belongs_to_many :livros
  attr_accessible :data_nascimento, :nome
end

app/models/endbibli.rb
class Endbibli < ActiveRecord::Base
	has_one :listbibli
    attr_accessible :rua, :bairro, :numero
  	validates_presence_of :rua
  	validates_presence_of :bairro
  	validates_presence_of :numero
end

app/models/listbibli.rb
class Listbibli < ActiveRecord::Base
  belongs_to :endbibli
  has_and_belongs_to_many :livros
  attr_accessible :nome, :telefone, :endbibli_id, :livro_ids
  validates_presence_of :nome, :telefone, :endbibli_id
    private
 # def validate_presence_of_more_than_one_restaurante
  #    errors.add("listbiblis"
   #     "deve haver ao menos uma listbiblis") if listbiblis.empty?
  #end
end

app/models/livro.rb
class Livro < ActiveRecord::Base

  has_and_belongs_to_many :autors
  has_and_belongs_to_many :listbiblis
  accepts_nested_attributes_for :autors, :reject_if => lambda{ |a| a[:nome].blank? }, :allow_destroy => true
  attr_accessible :data, :editora, :titulo, :pais, :autor_ids, :listbibli_ids, :autors_attributes


end

app/models/teste.rb
class Teste < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_accessible :password, :user
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :login, :senha

  def self.authenticate(login, senha)
	usuario = find_by_login(login)
	if usuario && usuario.senha == senha
		usuario
	else
		nil
	end
  end
end

app/models/usuario_session.rb
class UsuarioSession
	include ActiveModel::Validations
	include ActiveModel::Conversion

	attr_accessor :login, :senha
	validates_presence_of :login, :senha
	def persisted?
		false
	end
	def initialize(session, attributes={})
		@session = session
		@login = attributes[:login]
		@senha = attributes[:senha]
	end
	def authenticate
		usuario = Usuario.authenticate(@login, @senha)
		if usuario.present?
		store(usuario)
		else
		errors.add(:base, :invalid_login)
		false
		end
	end
	def store(usuario)
		@session[:usuario_id] = usuario.id
	end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
	def index
		@autor = Autor.all
	end
	def new
		@autor = Autor.new
	end
	def create
		@autor = Autor.new(params[:autor])
		if @autor.save
			redirect_to @autor, :notice => 'Autor Cadastrado'
			
		else
			render :new
		end
	end
	def show
		@autor = Autor.find(params[:id])
	end

	def edit
		@autor = Autor.find(params[:id])
	end

	def update
		@autor = Autor.find(params[:id])
		if @autor.update_attributes(params[:autor])
			redirect_to @autor, :notice => 'Cadastro atualizado com sucesso'
		else
			render :update
		end
	end
	def destroy
		@autor = Autor.find(params[:id])
		if @autor.destroy
			redirect_to @autor, :notice => 'Cadastro apagado'
		else
			render :index
		end
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def index
	
end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
	def index
		@livro = Livro.all
	end
	def new
		@livro = Livro.new
		3.times { @livro.autors.build }
	end
	def create
		@livro = Livro.new(params[:livro])
		if @livro.save
			redirect_to @livro, :notice => 'Livro Cadastrado'
			
		else
			render :new
		end
	end
	def show
		@livro = Livro.find(params[:id])
	end

	def edit
		@livro= Livro.find(params[:id])
	end

	def update
		@livro = Livro.find(params[:id])
		if @livro.update_attributes(params[:livro])
			redirect_to @livro, :notice => 'Cadastro atualizado com sucesso'
		else
			render :update
		end
	end
	def destroy
		@livro = Livro.find(params[:id])
		if @livro.destroy
			redirect_to @livros, :notice => 'Cadastro apagado'
		else
			render :index
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
			render(association.to_s.singularize + "_fields", :f => builder)
		end
		link_to_function(name, h("add_fields(this, \"#{association}\",\"#{escape_javascript_(fields)}\")"))
	end

end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/endbiblis_helper.rb
module EndbiblisHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/listbiblis_helper.rb
module ListbiblisHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/autors/_form.html.erb
<% if  @autors.errors.any? %>
<div id="error_explanation">
	<h2> Infelizmente não foi possivel completar a ação. </h2>
</div>
<% end %>
<div align="center">
<%=form_for @autor do |f| %>
	<p>
		<%= f.label :nome %>
		<%= f.text_field :nome %>
		<% if @autors.errors.has_key? :nome %>
		<div class="error_message">
		<%= @autors.errors[:nome].first %>
		<% end %>
		</div>
	</p>
	<div align="center">
	<p>
		<%= f.label :data_nascimento %>
		<%= f.date_select :data_nascimento %>
		<% if @autors.errors.has_key? :data_nascimento %>
		<div class="error_message">
		<%= @autors.errors[:data_nascimento].first %>
		<% end %>
		</div>
	</p>
	</div>
	<p>
		<div class="form-actions">
  		<button type="submit" class="btn btn-primary">Salvar</button>
  		<%= link_to autors_path do %>
  		<button type="button" class="btn">Cancelar</button>
  		<% end %>
		</div>
	</p>
<% end %>
</div>

app/views/autors/index.html.erb
<h1>Listando Autores</h1><br />
<div align="center">
<table border="1">
  <tr>
    <th width=30%>Nome</th>
    <th width=30>Dasta Nascimento</th>


  </tr>

<% @listbibli.each do |t| %>
  <tr>
    <td><%= t.nome%></td>
    <td><%= t.telefone%></td>
    <td><%= t.endbibli_id%></td>
    <td width=7%><%= link_to 'Mostrar', t %></td>
    <td width=7%><%= link_to 'Editar', edit_endbibli_path(t) %></td>
    <td width=7%><%= link_to 'Apagar', t, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class="btn-group">
  <%= link_to new_autor_path do %>
  <button class="btn">Novo Autor</button>
  <% end %>
  <%= link_to endbiblis_path do%>
  <button class="btn">Lista Endereços</button>
  <% end %>
</div>

app/views/autors/new.html.erb
<h1> Nova Biblioteca </h1>
<%= render 'form' %>

app/views/autors/show.html.erb
<h2> Autor: <%= @autor.id %> </h2>

<div>
<ul>
	<li> Nome: <%= @autor.nome %> </li>
	<li> Data de Nascimento: <%= @autor.data_nascimento %> </li>
</ul>

</div>

	<%= link_to edit_autor_path do %>
    <button class="btn">Editar Autor</button>
    <% end %>
    <%= link_to @autor, method: :delete, data: {confirm: 'Tem certeza?'} do %>
    <button class="btn btn-danger">Apagar Autor</button>
    <% end %>
    <%= link_to autors_path do%>
    <button class="btn">Voltar</button>
    <% end %>

app/views/livros/_autors_fields.html.erb
<p id="campo" class="fields">
	<%= f.label :nome, "Autor" %>
	<%= f.text_field :nome %>
</p>

app/views/livros/_form.html.erb
<% if  @livro.errors.any? %>
	<div id="error_explanation" align="center">
		<h2> Não foi possivel completar a ação. </h2>
	</div>
<% end %>
	<div align="center">
	<%=form_for @livro do |f| %>
		<p>
			<%= f.label :titulo %>
			<%= f.text_field :titulo %>
			<% if @livro.errors.has_key? :titulo %>
			<div class="error_message">
				<%= @livro.errors[:titulo].first %>
			<% end %>
			</div>
		</p>
			<p>
			<%= f.label :editora %>
			<%= f.text_field :editora %>
			<% if @livro.errors.has_key? :editora %>
			<div class="error_message">
				<%= @livro.errors[:editora].first %>
			<% end %>
			</div>
		</p>
		<div align="center">
		<p>
			<%= f.label :pais %>
			<%= f.text_field :pais %>
			<% if @livro.errors.has_key? :pais %>
			<div class="error_message">
				<%= @livro.errors[:pais].first %>
			<% end %>
			</div>
		</p>
		<p>
			<%= f.label :data %>
			<%= f.date_select :data %>
			<% if @livro.errors.has_key? :data %>
			<div class="error_message">
				<%= @livro.errors[:data].first %>
			<% end %>
			</div>
		</p>
		<p>
			<h3> Selecione as bibliotecas que contém o livro </h3>
			<% Listbibli.all.each do |d|%>		
				<p><%= check_box_tag "livro[listbibli_ids][]", d.id, @livro.listbiblis.include?(d) %> <%= d.nome %> </p>
			<% end %>
			<br/>
		</p>
		<h3> Autor(es) </h3>
		<p>
			<%= f.fields_for :autors do |builder| %>
			<%= render 'autors_fields', f: builder %>
			<%end%>


		</p>
		</div>
		<p>
			<div class="form-actions">
	  			<button type="submit" class="btn btn-primary">Salvar</button>
	  			<%= link_to endbiblis_path do%>
	  				<button type="button" class="btn">Cancelar</button>
	  			<% end %>
			</div>
		</p>


	</div>
<% end %>

app/views/livros/edit.html.erb
<h1> Editar Livro </h1>
<%= render 'form'%>

app/views/livros/index.html.erb
<h1>Listando Livros</h1><br />
<div align="center">
<table border="1">
  <tr>
    <th width=3%>Id</th>
    <th width=30%>Titulo</th>
    <th width=30%>Editora</th>
    <th width=10%>Pais</th>
    <th width=10%>Data</th>
  </tr>

<% @livro.each do |t| %>
  <tr>
    <td><%= t.id%></td>
    <td><%= t.titulo%></td>
    <td><%= t.editora%></td>
    <td><%= t.pais%></td>   
    <td><%= t.data%></td>
    <td><%= link_to 'Mostrar', t %></td>
    <td><%= link_to 'Editar', edit_livro_path(t) %></td>
    <td><%= link_to 'Apagar', t, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />
<div class="btn-group">
  <%= link_to new_livro_path do%>
  <button class="btn">Novo Livro</button>
  <%end%>
  <%= link_to listbiblis_path do%>
  <button class="btn">Lista Bibliotecas</button>
  <%end%>
</div>

app/views/livros/new.html.erb
<h1> Novo Livro </h1>
<%= render 'form' %>

app/views/livros/show.html.erb
<h2> Livro: <%= @livro.titulo%> </h2>
<ul>
	<li> Editora: <%= @livro.editora %> </li>
	<li> Pais: <%= @livro.pais %> </li>
	<li> Data: <%= @livro.data %> </li>
  <h4> Bibliotecas que contem o livro:</h4>
  <% Listbibli.all.each do |b|%>
  <% if @livro.listbiblis.include?(b)%>
    <li> <%= b.nome %> </li>
  <%end%>
  <%end%>
</ul>
<h4>Autor(es):</h4>
<ul>
    <% for autor in @livro.autors %>
        <li> <%= autor.nome %>
    <%end%>
</ul>
	  <%= link_to edit_livro_path do %>
  	<button class="btn">Editar Endereço</button>
  	<% end %>
  	<%= link_to @livro, method: :delete, data: {confirm: 'Tem certeza?'} do %>
  	<button class="btn btn-danger">Apagar Endereço</button>
  	<% end %>
  	<%= link_to livros_path do %>
  	<button class="btn">Voltar</button>
    <%end%>