config/routes.rb
Biblioteca::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
   get "sign_in" => "usuarios#new", :as => "sign_in"
  resources :sessions
  resources :testes
  resources :endbiblis
  resources :listbiblis
  resources :autors
  resources :livros
  resources :listbiblis_livros
  resources :autors_livros
  resources :usuarios
  resource :confirmation, :only => [:show]
  resource :usuario_sessions, :only => [:create, :new, :destroy]
  root :to => "homes#index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base
  has_and_belongs_to_many :livros
  attr_accessible :data_nascimento, :nome
end

app/models/endbibli.rb
class Endbibli < ActiveRecord::Base
	has_one :listbibli
    attr_accessible :rua, :bairro, :numero
  	validates_presence_of :rua
  	validates_presence_of :bairro
  	validates_presence_of :numero
end

app/models/listbibli.rb
class Listbibli < ActiveRecord::Base
  belongs_to :endbibli
  has_and_belongs_to_many :livros
  attr_accessible :nome, :telefone, :endbibli_id, :livro_ids
  validates_presence_of :nome, :telefone, :endbibli_id
    private
 # def validate_presence_of_more_than_one_restaurante
  #    errors.add("listbiblis"
   #     "deve haver ao menos uma listbiblis") if listbiblis.empty?
  #end
end

app/models/livro.rb
class Livro < ActiveRecord::Base

  has_and_belongs_to_many :autors
  has_and_belongs_to_many :listbiblis
  accepts_nested_attributes_for :autors, :reject_if => lambda{ |a| a[:nome].blank? }, :allow_destroy => true
  attr_accessible :data, :editora, :titulo, :pais, :autor_ids, :listbibli_ids, :autors_attributes


end

app/models/teste.rb
class Teste < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_accessible :password, :user
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :login, :senha

  def self.authenticate(login, senha)
	usuario = find_by_login(login)
	if usuario && usuario.senha == senha
		usuario
	else
		nil
	end
  end
end

app/models/usuario_session.rb
class UsuarioSession
	include ActiveModel::Validations
	include ActiveModel::Conversion

	attr_accessor :login, :senha
	validates_presence_of :login, :senha
	def persisted?
		false
	end
	def initialize(session, attributes={})
		@session = session
		@login = attributes[:login]
		@senha = attributes[:senha]
	end
	def authenticate
		usuario = Usuario.authenticate(@login, @senha)
		if usuario.present?
		store(usuario)
		else
		errors.add(:base, :invalid_login)
		false
		end
	end
	def store(usuario)
		@session[:usuario_id] = usuario.id
	end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
	def index
		@autor = Autor.all
	end
	def new
		@autor = Autor.new
	end
	def create
		@autor = Autor.new(params[:autor])
		if @autor.save
			redirect_to @autor, :notice => 'Autor Cadastrado'
			
		else
			render :new
		end
	end
	def show
		@autor = Autor.find(params[:id])
	end

	def edit
		@autor = Autor.find(params[:id])
	end

	def update
		@autor = Autor.find(params[:id])
		if @autor.update_attributes(params[:autor])
			redirect_to @autor, :notice => 'Cadastro atualizado com sucesso'
		else
			render :update
		end
	end
	def destroy
		@autor = Autor.find(params[:id])
		if @autor.destroy
			redirect_to @autor, :notice => 'Cadastro apagado'
		else
			render :index
		end
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def index
	
end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
		def index
		@usuario = Usuario.all
	end
	def new
		@usuario = Usuario.new
	end
	def create
		@usuario = Usuario.new(params[:usuario])
		if @usuario.save
			redirect_to @usuario, :notice => 'Usuario Cadastrado'
			
		else
			render :new
		end
	end
	def show
		@usuario = Usuario.new
	end

	def edit
		@usuario = Usuario.find(params[:id])
	end

	def update
		@usuario = Usuario.find(params[:id])
		if @usuario.update_attributes(params[:usuario])
			redirect_to @usuario, :notice => 'Cadastro atualizado com sucesso'
		else
			render :update
		end
	end
	def destroy
		@usuario = Usuario.find(params[:id])
		if @usuario.destroy
			redirect_to @usuario, :notice => 'Cadastro apagado'
		else
			render :index
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
			render(association.to_s.singularize + "_fields", :f => builder)
		end
		link_to_function(name, h("add_fields(this, \"#{association}\",\"#{escape_javascript_(fields)}\")"))
	end

end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/endbiblis_helper.rb
module EndbiblisHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/listbiblis_helper.rb
module ListbiblisHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<% if  @usuario.errors.any? %>
<div id="error_explanation">
	<h2> Infelizmente não foi possivel completar a ação. </h2>
</div>
<% end %>
<div align="center">
<%=form_for @usuario do |f| %>
	<p>
		<%= f.label :login %>
		<%= f.text_field :login %>
		<% if @usuario.errors.has_key? :login %>
		<div class="error_message">
		<%= @usuario.errors[:login].first %>
		<% end %>
		</div>
	</p>
	<div align="center">
	<p>
		<%= f.label :senha %>
		<%= f.password_field :senha %>
		<% if @usuario.errors.has_key? :senha %>
		<div class="error_message">
		<%= @usuario.errors[:senha].first %>
		<% end %>
		</div>
	</p>
	</div>
	<p>
		<div class="form-actions">
  		<button type="submit" class="btn btn-primary">Salvar</button>
  		<%= link_to new_sessions_path do %>
  		<button type="button" class="btn">Cancelar</button>
  		<% end %>
		</div>
	</p>
	
<% end %>
</div>

app/views/usuarios/edit.html.erb
<h1> Editar Autor </h1>
<%= render 'form'%>

app/views/usuarios/index.html.erb
<h1>Listando Usuarios Cadastrados</h1><br />
<div align="center">
<table border="1">
<ul>
<% @usuario.each do |t| %>

  <li> <%= t.login %></li>

<% end %>
</ul>
</table>

<br />

<div class="btn-group">
  <%= link_to new_usuario_path do %>
  <button class="btn">Novo usuario</button>
  <% end %>
  <%= link_to new_session_path do%>
  <button class="btn">Login</button>
  <% end %>
</div>

app/views/usuarios/login.html.erb
<h1>Home</h1>
<% lo = "asd" %>
<% lo = "asd"%>
<%=form_for @usuarios do |f| %>
	<p>
		<%= f.label :login %>
		<%= f.text_field lo %>
	</p>
	<p>
		<%= f.label :senha %>
		<%= f.text_field se %>
	</p>
<%end%>

app/views/usuarios/new.html.erb
<h1> Cadastrar Usuario </h1>
<%= render 'form' %>

app/views/usuarios/show.html.erb
<h1>Home</h1>
<%=form_for @usuario do |f| %>
    <p>
        <%= f.label :login %>
        <%= f.text_field :login %>
    </p>
    <p>
        <%= f.label :senha %>
        <%= f.text_field :senha %>
    </p>
<%end%>
    <p>
        <div class="form-actions">
        <button type="submit" class="btn btn-primary">Salvar</button>
        <%= link_to autors_path do %>
        <button type="button" class="btn">Cancelar</button>
        <% end %>
        </div>
    </p>