config/routes.rb
Biblioteca::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
   get "sign_in" => "usuarios#new", :as => "sign_in"
  resources :sessions
  resources :testes
  resources :endbiblis
  resources :listbiblis
  resources :autors
  resources :livros
  resources :listbiblis_livros
  resources :autors_livros
  resources :usuarios
  resource :confirmation, :only => [:show]
  resource :usuario_sessions, :only => [:create, :new, :destroy]
  root :to => "homes#index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base
  has_and_belongs_to_many :livros
  attr_accessible :data_nascimento, :nome
end

app/models/endbibli.rb
class Endbibli < ActiveRecord::Base
	has_one :listbibli
    attr_accessible :rua, :bairro, :numero
  	validates_presence_of :rua
  	validates_presence_of :bairro
  	validates_presence_of :numero
end

app/models/listbibli.rb
class Listbibli < ActiveRecord::Base
  belongs_to :endbibli
  has_and_belongs_to_many :livros
  attr_accessible :nome, :telefone, :endbibli_id, :livro_ids
  validates_presence_of :nome, :telefone, :endbibli_id
    private
 # def validate_presence_of_more_than_one_restaurante
  #    errors.add("listbiblis"
   #     "deve haver ao menos uma listbiblis") if listbiblis.empty?
  #end
end

app/models/livro.rb
class Livro < ActiveRecord::Base

  has_and_belongs_to_many :autors
  has_and_belongs_to_many :listbiblis
  accepts_nested_attributes_for :autors, :reject_if => lambda{ |a| a[:nome].blank? }, :allow_destroy => true
  attr_accessible :data, :editora, :titulo, :pais, :autor_ids, :listbibli_ids, :autors_attributes


end

app/models/teste.rb
class Teste < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_accessible :password, :user
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :login, :senha

  def self.authenticate(login, senha)
	usuario = find_by_login(login)
	if usuario && usuario.senha == senha
		usuario
	else
		nil
	end
  end
end

app/models/usuario_session.rb
class UsuarioSession
	include ActiveModel::Validations
	include ActiveModel::Conversion

	attr_accessor :login, :senha
	validates_presence_of :login, :senha
	def persisted?
		false
	end
	def initialize(session, attributes={})
		@session = session
		@login = attributes[:login]
		@senha = attributes[:senha]
	end
	def authenticate
		usuario = Usuario.authenticate(@login, @senha)
		if usuario.present?
		store(usuario)
		else
		errors.add(:base, :invalid_login)
		false
		end
	end
	def store(usuario)
		@session[:usuario_id] = usuario.id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
			render(association.to_s.singularize + "_fields", :f => builder)
		end
		link_to_function(name, h("add_fields(this, \"#{association}\",\"#{escape_javascript_(fields)}\")"))
	end

end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/endbiblis_helper.rb
module EndbiblisHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/listbiblis_helper.rb
module ListbiblisHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Biblioteca Project</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag 'application'%>
<%= csrf_meta_tags %>
</head>
<body>
<header class="well	">
<h1><%= link_to "Bibliotecas", root_path %> </h1>
  <%= link_to root_path do %>
  <button class="btn">Home</button>
  <% end %>
  <%= link_to listbiblis_path do %>
  <button class="btn">Bibliotecas</button>
  <% end %>
  <%= link_to new_listbibli_path do %>
  <button class="btn">Nova Biblioteca</button>
  <% end %>
  <%= link_to endbiblis_path do %>
  <button class="btn">Endereços</button>
  <% end %>
  <%= link_to livros_path do %>
  <button class="btn">Livros</button>
  <% end %>
    <%= link_to usuarios_path do %>
  <button class="btn">Usuarios</button>
  <% end %>
      <%= link_to new_session_path do %>
  <button class="btn">Login</button>
  <% end %>
</div>
</header>
<div id="content">
<% if notice.present? %>
<p id="notice"><%= notice %> </p>
<% end %>
<% if alert.present? %>
<p id="alert"><%= alert %> </p>
<% end %>
<%= yield %>
</div>

</body>
</html>